version: "3"
services:
  zookeeper:
    image: "bitnami/zookeeper:3.7.2"
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - ./.data/zookeeper/data:/bitnami/zookeeper/data
      - ./.data/zookeeper/datalog:/bitnami/zookeeper/datalog
      - ./.data/zookeeper/logs:/bitnami/zookeeper/logs
    networks:
      - kafka_network
  kafka:
    image: "bitnami/kafka:3.6.0"
    container_name: kafka
    hostname: kafka
    user: root
    ports:
      - 19092
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:19092,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:19092,EXTERNAL://43.201.213.254:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
    volumes:
      - ./.data/kafka1:/bitnami/kafka/data
    networks:
      - kafka_network
  ## kafka-ui tool
  kafka-ui:
    image: "provectuslabs/kafka-ui:v0.7.1"
    container_name: kafka-ui
    ports:
      - "8081:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:19092
      - KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME=kafka-connecto
      - KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS=http://connect:8083

    depends_on:
      - zookeeper
      - kafka
    networks:
      - kafka_network
  mysql:
    image: "mysql:8.0.35"
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=users
      - MYSQL_USER=dobby
      - MYSQL_PASSWORD=1234
    command: --server-id=1 --log-bin=/var/lib/mysql/mysql-bin.log --binlog_format=ROW
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      kafka_network:
        ipv4_address: 172.20.0.5
  ## connect
  connect:
    image: debezium/connect:2.7.3.Final
    container_name: debezium-connect
    ports:
      - "8083:8083"
    environment:
      GROUP_ID: "1"
      CONFIG_STORAGE_TOPIC: "connect_configs"
      OFFSET_STORAGE_TOPIC: "connect_offsets"
      STATUS_STORAGE_TOPIC: "connect_statuses"
      BOOTSTRAP_SERVERS: "kafka:19092"
      KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      REST_ADVERTISED_HOST_NAME: "connect"
      CONNECT_REST_PORT: "8083"
    networks:
      kafka_network:
        ipv4_address: 172.20.0.20

volumes:
  mysql-volume:

networks:
  kafka_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
